//! Model-participant bridge: a local model joins a meeting room as a live chat
//! participant alongside humans. Spec: `docs/specs/demo-conference.md`.
//!
//! The bridge is *just a meeting client* — it reads the room transcript and
//! `meeting.submit`s replies through the existing daemon, holding no model
//! in-process: replies are generated by the local `rozum gateway`
//! (OpenAI `/v1/chat/completions`). It is never the room's writer and adds no
//! moderation/turn-taking — *when* it speaks is a per-participant policy, so the
//! daemon's single-writer / no-moderator invariants stay intact.
//!
//! The join/poll/reply-policy loop itself lives in
//! [`super::participant_loop`] — shared with [`super::agent_participant`], which
//! answers by running `claude`/`nadia`/`codex` instead of calling the gateway.

use std::future::Future;
use std::pin::Pin;
use std::time::Duration;

use super::participant_loop::{
    ParticipantConfig, ReplyGenerator, ReplyPolicy, run_participant_loop, sender_id_from_content,
    strip_mention,
};
use super::store::StoredTurn;

/// Build the chat-completion message list from the recent transcript: the system prompt, then the
/// last ~24 turns (oldest→newest) as user/assistant messages. Drops roster presence lines and
/// redaction placeholders, and dedupes our OWN repeated assistant outputs — ≥4 identical assistant
/// turns would otherwise trip the gateway's stuck-loop detector, which then emits the same "stuck"
/// text and poisons the model into repeating it.
fn build_context(
    system: String,
    transcript: &[StoredTurn],
    handle: &str,
    mention_alias: Option<&str>,
) -> Vec<serde_json::Value> {
    let mut messages = vec![serde_json::json!({ "role": "system", "content": system })];
    let start = transcript.len().saturating_sub(24);
    let mut seen_assistant: std::collections::HashSet<String> = std::collections::HashSet::new();
    for t in &transcript[start..] {
        let c = t.content.trim_start();
        if c.starts_with("joined:") || c.starts_with("left:") || c.starts_with("[redacted") {
            continue;
        }
        let who = super::participant_loop::base_handle(&t.display_name);
        if who.eq_ignore_ascii_case(handle) {
            let key = t.content.trim().to_string();
            if key.is_empty() || !seen_assistant.insert(key) {
                continue; // skip empty and already-seen (duplicate) assistant turns
            }
            messages.push(serde_json::json!({ "role": "assistant", "content": t.content }));
        } else {
            // Strip the bot's own @mention so the model sees a clean question, not "@Rozum_chat_bot …".
            let content = strip_mention(&t.content, mention_alias);
            messages.push(serde_json::json!({
                "role": "user",
                "content": format!("{}: {}", who, content),
            }));
        }
    }
    messages
}

/// The gateway-backed reply generator: HTTP chat-completions, with an optional
/// per-user-gated tool-calling loop against `sandbox_tools::Sandbox`. This struct is
/// exactly the state `run()` used to close over in the old inline loop.
struct ModelReplier {
    gateway_url: String,
    model: String,
    handle: String,
    persona: Option<String>,
    sandbox: Option<super::sandbox_tools::Sandbox>,
    shell: bool,
    acl_path: Option<std::path::PathBuf>,
    mention_alias: Option<String>,
}

impl ReplyGenerator for ModelReplier {
    fn reply<'a>(
        &'a mut self,
        history: &'a [StoredTurn],
        turn: &'a StoredTurn,
    ) -> Pin<Box<dyn Future<Output = Option<String>> + Send + 'a>> {
        Box::pin(async move {
            // Per-user tool capabilities: when an ACL is configured, the file/shell tools
            // offered for THIS reply are gated by the triggering messenger user's grants
            // (parsed from the `[name #id]:` prefix the bridge submits). Without an ACL,
            // the sandbox defaults to read+write (+shell only if --shell).
            let (can_read, can_write, can_shell) = match &self.acl_path {
                Some(path) => match sender_id_from_content(&turn.content) {
                    Some(id) => {
                        let caps = super::super::messenger_acl::Acl::load(path).caps_for(id);
                        (caps.read, caps.write, caps.shell && self.shell)
                    }
                    // No parseable messenger sender (e.g. a local TUI turn) → no tools.
                    None => (false, false, false),
                },
                None => (true, true, self.shell),
            };
            match generate(
                &self.gateway_url,
                &self.model,
                history,
                &self.handle,
                self.persona.as_deref(),
                self.sandbox.as_ref(),
                can_read,
                can_write,
                can_shell,
                self.mention_alias.as_deref(),
            )
            .await
            {
                Ok(text) if !text.trim().is_empty() => Some(text.trim().to_string()),
                Ok(_) => None,
                Err(e) => {
                    eprintln!("[participant] generate failed (staying silent): {e}");
                    None
                }
            }
        })
    }
}

/// Run the bridge: join `room` as `handle`, then reply via the gateway per `policy`
/// until the connection closes.
#[allow(clippy::too_many_arguments)]
pub async fn run(
    model: String,
    room: String,
    handle: String,
    policy: ReplyPolicy,
    gateway_url: String,
    peers: Vec<String>,
    persona: Option<String>,
    sandbox: Option<std::path::PathBuf>,
    shell: bool,
    shell_network: bool,
    acl_path: Option<std::path::PathBuf>,
    mention_alias: Option<String>,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // Optional file/shell tools confined to one directory (opt-in via --sandbox). A failure to
    // open the directory degrades to chat-only rather than crashing the room.
    let sandbox = sandbox.and_then(|p| match super::sandbox_tools::Sandbox::open(&p) {
        Ok(sb) => {
            let sb = sb.with_network(shell_network);
            eprintln!(
                "[participant] sandbox: file tools enabled at {} (shell network {})",
                sb.root().display(),
                if shell_network { "allowed" } else { "denied" }
            );
            Some(sb)
        }
        Err(e) => {
            eprintln!(
                "[participant] sandbox {}: {e} — running chat-only (no file tools)",
                p.display()
            );
            None
        }
    });
    if let Some(path) = &acl_path {
        eprintln!(
            "[participant] per-user capabilities from ACL {} (shell {})",
            path.display(),
            if shell { "enabled" } else { "disabled" }
        );
    }

    let replier = ModelReplier {
        gateway_url: gateway_url.clone(),
        model: model.clone(),
        handle: handle.clone(),
        persona,
        sandbox,
        shell,
        acl_path,
        mention_alias: mention_alias.clone(),
    };
    let cfg = ParticipantConfig {
        room,
        handle,
        label: format!("model {model}"),
        policy,
        peers,
        mention_alias,
        identity_prefix: "model-participant",
    };
    run_participant_loop(cfg, replier).await
}

/// Max model→tool→model rounds per reply before we stop and return text. Bounds a
/// model that keeps calling tools without ever answering (weak-model loop guard).
const MAX_TOOL_ROUNDS: usize = 6;

/// Generate a reply from the local model via the gateway's OpenAI chat endpoint,
/// using the recent transcript (oldest→newest) as conversation context. When
/// `sandbox` is set the model is given file/shell tools confined to that dir and
/// its tool-calls are executed and fed back until it produces a text answer.
#[allow(clippy::too_many_arguments)]
async fn generate(
    gateway_url: &str,
    model: &str,
    transcript: &[StoredTurn],
    handle: &str,
    persona: Option<&str>,
    sandbox: Option<&super::sandbox_tools::Sandbox>,
    can_read: bool,
    can_write: bool,
    can_shell: bool,
    mention_alias: Option<&str>,
) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
    // File/shell tools are offered only when a sandbox exists AND this user was granted the
    // capability. When nothing is granted the model runs as plain chat (no tools).
    let (read, write, shell) = match sandbox {
        Some(_) => (can_read, can_write, can_shell),
        None => (false, false, false),
    };
    let tools_on = read || write || shell;

    // Chat mechanics are always present; an operator-supplied `--persona` prepends WHO the model
    // is + any domain context (e.g. about rozum/busi) so it answers on-topic instead of generically.
    let mechanics = "Reply briefly and directly to the most recent message — actually answer the \
        question or contribute something substantive; do NOT deflect with 'how can I help' or 'what \
        would you like to explore'. Messages from others are prefixed with their name; your own are \
        not. Do NOT prefix your reply with your name.";
    let mut system = match persona {
        Some(p) if !p.trim().is_empty() => format!("{}\n\n{mechanics}", p.trim()),
        _ => format!("You are {handle}, an AI participant in a multi-person group chat. {mechanics}"),
    };
    // With tools available, tell the model which ones so it USES them instead of claiming it has
    // no filesystem access. Only advertise the capabilities this user actually has.
    if tools_on {
        let mut names = Vec::new();
        if read {
            names.push("list_files, read_file");
        }
        if write {
            names.push("write_file");
        }
        if shell {
            names.push("run_command");
        }
        // Discriminate strictly: a weak model otherwise reflexively calls a tool for every message
        // (and loops). Tools ONLY for actual file/command actions; questions get a text answer.
        system.push_str(&format!(
            "\n\nYou have a working directory with these tools: {}. Paths are relative to it. \
             Call a tool ONLY when the user asks to DO something with files or run a command \
             (create/read/change/list a file, run a command). For ordinary questions — including \
             about the project, yourself, or general chat — answer with TEXT and do NOT call any \
             tool. After a tool returns, give a short text answer; never call the same tool twice \
             in a row.",
            names.join(", ")
        ));
    }
    let messages = build_context(system, transcript, handle, mention_alias);
    // A strict chat template (e.g. Qwen3.6) errors without a user message — if the context held
    // only presence/own turns, there's nothing to answer; stay silent rather than send a bad call.
    if !messages.iter().any(|m| m["role"] == "user") {
        return Ok(String::new());
    }
    let mut messages = messages;

    let url = format!("{}/chat/completions", gateway_url.trim_end_matches('/'));
    let http = reqwest::Client::new();
    let tools = if tools_on {
        Some(super::sandbox_tools::Sandbox::tool_defs(read, write, shell))
    } else {
        None
    };
    // Tool mode may need to emit file contents (tool arguments count as output) — give it more
    // room than a chat one-liner.
    let max_tokens = if tools_on { 2048 } else { 400 };

    // Signature of the previous round's tool calls — if a round repeats it verbatim, the weak model
    // is stuck; stop and force a plain text answer instead of spinning into the loop-breaker.
    let mut last_sig: Option<String> = None;
    for _round in 0..MAX_TOOL_ROUNDS {
        let mut body = serde_json::json!({
            "model": model, "messages": messages, "max_tokens": max_tokens, "stream": false,
        });
        if let Some(t) = &tools {
            body["tools"] = t.clone();
        }
        let resp = http
            .post(&url)
            .json(&body)
            .timeout(Duration::from_secs(180))
            .send()
            .await?;
        if !resp.status().is_success() {
            let status = resp.status();
            return Err(
                format!("gateway {status}: {}", resp.text().await.unwrap_or_default()).into(),
            );
        }
        let json: serde_json::Value = resp.json().await?;
        let msg = &json["choices"][0]["message"];
        let content = msg["content"].as_str().unwrap_or("").to_string();
        let calls = msg["tool_calls"].as_array().filter(|c| !c.is_empty());

        // No sandbox, or the model answered instead of calling a tool → return its text.
        let (Some(sb), Some(calls)) = (sandbox, calls) else {
            return Ok(content);
        };

        // Repeat guard: identical tool call(s) to the previous round → no progress, stop looping.
        let sig = calls
            .iter()
            .map(|c| {
                format!(
                    "{}:{}",
                    c["function"]["name"].as_str().unwrap_or(""),
                    c["function"]["arguments"].as_str().unwrap_or("")
                )
            })
            .collect::<Vec<_>>()
            .join("|");
        if last_sig.as_deref() == Some(sig.as_str()) {
            break;
        }
        last_sig = Some(sig);

        // Echo the assistant's tool-call turn, then run each call in the sandbox and feed the
        // result back as a `tool` message so the next round sees it.
        messages.push(serde_json::json!({
            "role": "assistant",
            "content": content,
            "tool_calls": calls.clone(),
        }));
        for call in calls {
            let id = call["id"].as_str().unwrap_or("");
            let name = call["function"]["name"].as_str().unwrap_or("");
            let args: serde_json::Value = call["function"]["arguments"]
                .as_str()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_else(|| serde_json::json!({}));
            let result = sb.dispatch(name, &args).await;
            eprintln!("[participant] tool {name} → {} bytes", result.len());
            messages.push(serde_json::json!({
                "role": "tool",
                "tool_call_id": id,
                "content": result,
            }));
        }
    }

    // The tool budget ran out (or the model got stuck): make ONE final tool-less call so the user
    // gets a clean text answer from the results gathered so far, not a loop-breaker artifact.
    messages.push(serde_json::json!({
        "role": "user",
        "content": "Ответь пользователю кратким текстом по результатам инструментов выше. \
                    Не вызывай инструменты.",
    }));
    let body = serde_json::json!({
        "model": model, "messages": messages, "max_tokens": max_tokens, "stream": false,
    });
    let resp = http
        .post(&url)
        .json(&body)
        .timeout(Duration::from_secs(180))
        .send()
        .await?;
    if !resp.status().is_success() {
        return Ok(String::new());
    }
    let json: serde_json::Value = resp.json().await?;
    Ok(json["choices"][0]["message"]["content"].as_str().unwrap_or("").to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn turn(name: &str, content: &str) -> StoredTurn {
        StoredTurn {
            date: "2026-06-20".into(),
            n: 1,
            participant_id: "x".into(),
            display_name: name.into(),
            content: content.into(),
            ts: 0,
            ..Default::default()
        }
    }

    #[test]
    fn build_context_dedupes_own_turns_and_drops_noise() {
        let transcript = vec![
            turn("qwen", "joined: I'm qwen"),
            turn("Sergiy", "вопрос 1"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "[redacted: old]"),
            turn("Sergiy", "вопрос 2"),
        ];
        let msgs = build_context("SYS".into(), &transcript, "qwen", None);
        let asst_stuck = msgs
            .iter()
            .filter(|m| m["role"] == "assistant" && m["content"] == "STUCK LOOP TEXT")
            .count();
        assert_eq!(asst_stuck, 1, "4 identical assistant turns collapse to one");
        assert!(!msgs.iter().any(|m| m["content"].as_str().unwrap_or("").contains("joined:")));
        assert!(!msgs.iter().any(|m| m["content"].as_str().unwrap_or("").contains("[redacted")));
        assert_eq!(msgs.iter().filter(|m| m["role"] == "user").count(), 2);
    }
}
