//! Model-participant bridge: a local model joins a meeting room as a live chat
//! participant alongside humans. Spec: `docs/specs/demo-conference.md`.
//!
//! The bridge is *just a meeting client* — it reads the room transcript and
//! `meeting.submit`s replies through the existing daemon, holding no model
//! in-process: replies are generated by the local `rozum gateway`
//! (OpenAI `/v1/chat/completions`). It is never the room's writer and adds no
//! moderation/turn-taking — *when* it speaks is a per-participant policy, so the
//! daemon's single-writer / no-moderator invariants stay intact.

use std::time::Duration;

use super::room_path::meeting_sock;
use super::store::StoredTurn;
use super::tui_client::MeetingClient;

/// When the model contributes. A politeness policy of ONE participant — never a
/// room-level moderator or turn-scheduler (global meeting invariant).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReplyPolicy {
    /// Reply only when the model's handle is `@mentioned` (safe multi-model default).
    Mention,
    /// Reply to any new human message (never its own or a peer model's — loop guard).
    Always,
    /// Never reply on its own (driven externally).
    Manual,
}

impl std::str::FromStr for ReplyPolicy {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, String> {
        match s.trim().to_ascii_lowercase().as_str() {
            "mention" => Ok(Self::Mention),
            "always" => Ok(Self::Always),
            "manual" => Ok(Self::Manual),
            other => Err(format!("unknown reply-policy '{other}' (mention|always|manual)")),
        }
    }
}

/// Derive a clean roster handle from a model spec: the last path/spec segment up to
/// the size/version suffix. `mlx-community:gpt-oss-20b-MXFP4-Q4` → `gpt-oss`;
/// `mlx-community:Qwen3.6-35B-A3B-4bit` → `qwen3.6`.
pub fn derive_handle(model: &str) -> String {
    let seg = model.rsplit([':', '/']).next().unwrap_or(model);
    let mut out = String::new();
    let chars: Vec<char> = seg.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        // Stop at a `-<digit>` (size/quant suffix like `-20b`, `-35B`).
        if chars[i] == '-' && chars.get(i + 1).is_some_and(|c| c.is_ascii_digit()) {
            break;
        }
        out.push(chars[i]);
        i += 1;
    }
    let h = if out.is_empty() { seg.to_string() } else { out };
    h.to_ascii_lowercase()
}

/// The stable base of a roster display name — the daemon appends a session suffix
/// (`gpt-oss · jolly-marten` → `gpt-oss`), so compare on the base, not the full name.
pub fn base_handle(display: &str) -> &str {
    display.split('·').next().map(str::trim).unwrap_or(display)
}

/// Build the chat-completion message list from the recent transcript: the system prompt, then the
/// last ~24 turns (oldest→newest) as user/assistant messages. Drops roster presence lines and
/// redaction placeholders, and dedupes our OWN repeated assistant outputs — ≥4 identical assistant
/// turns would otherwise trip the gateway's stuck-loop detector, which then emits the same "stuck"
/// text and poisons the model into repeating it.
fn build_context(system: String, transcript: &[StoredTurn], handle: &str) -> Vec<serde_json::Value> {
    let mut messages = vec![serde_json::json!({ "role": "system", "content": system })];
    let start = transcript.len().saturating_sub(24);
    let mut seen_assistant: std::collections::HashSet<String> = std::collections::HashSet::new();
    for t in &transcript[start..] {
        let c = t.content.trim_start();
        if c.starts_with("joined:") || c.starts_with("left:") || c.starts_with("[redacted") {
            continue;
        }
        let who = base_handle(&t.display_name);
        if who.eq_ignore_ascii_case(handle) {
            let key = t.content.trim().to_string();
            if key.is_empty() || !seen_assistant.insert(key) {
                continue; // skip empty and already-seen (duplicate) assistant turns
            }
            messages.push(serde_json::json!({ "role": "assistant", "content": t.content }));
        } else {
            messages.push(serde_json::json!({
                "role": "user",
                "content": format!("{}: {}", who, t.content),
            }));
        }
    }
    messages
}

/// Parse the numeric messenger sender id from a bridge-submitted turn. Bridges
/// submit `[<display> #<id>]: <text>`; extract `<id>` so the participant can look
/// up that user's capabilities. Returns None for non-bridge turns (no prefix).
fn sender_id_from_content(content: &str) -> Option<i64> {
    let content = content.trim_start();
    let close = content.strip_prefix('[')?.find(']')?;
    let head = &content[1..=close]; // "<display> #<id>"
    let hash = head.rfind('#')?;
    head[hash + 1..].trim_end_matches(']').trim().parse::<i64>().ok()
}

/// Should the model reply to `turn`? `handle` is its own base handle (callers have
/// already excluded its own turns). `peers` are other model handles in the room, so
/// `Always` never triggers a model↔model runaway.
pub fn should_reply(policy: ReplyPolicy, turn: &StoredTurn, handle: &str, peers: &[String]) -> bool {
    match policy {
        ReplyPolicy::Manual => false,
        ReplyPolicy::Mention => turn
            .content
            .to_ascii_lowercase()
            .contains(&format!("@{}", handle.to_ascii_lowercase())),
        ReplyPolicy::Always => {
            let from = base_handle(&turn.display_name);
            !peers.iter().any(|p| p.eq_ignore_ascii_case(from))
        }
    }
}

/// Run the bridge: join `room` as `handle`, then reply via the gateway per `policy`
/// until the connection closes. Errors generating a reply are logged and swallowed —
/// a gateway hiccup must never crash the room.
#[allow(clippy::too_many_arguments)]
pub async fn run(
    model: String,
    room: String,
    handle: String,
    policy: ReplyPolicy,
    gateway_url: String,
    peers: Vec<String>,
    persona: Option<String>,
    sandbox: Option<std::path::PathBuf>,
    shell: bool,
    acl_path: Option<std::path::PathBuf>,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    use super::daemon::daemon_alive;
    use super::daemon_proxy::spawn_daemon;

    // Optional file/shell tools confined to one directory (opt-in via --sandbox). A failure to
    // open the directory degrades to chat-only rather than crashing the room.
    let sandbox = sandbox.and_then(|p| match super::sandbox_tools::Sandbox::open(&p) {
        Ok(sb) => {
            eprintln!("[participant] sandbox: file tools enabled at {}", sb.root().display());
            Some(sb)
        }
        Err(e) => {
            eprintln!(
                "[participant] sandbox {}: {e} — running chat-only (no file tools)",
                p.display()
            );
            None
        }
    });
    if let Some(path) = &acl_path {
        eprintln!(
            "[participant] per-user capabilities from ACL {} (shell {})",
            path.display(),
            if shell { "enabled" } else { "disabled" }
        );
    }

    let sock = meeting_sock();
    if !daemon_alive(&sock).await {
        spawn_daemon().await;
    }
    // Stable identity per handle → ONE roster participant across restarts.
    let token = format!("model-participant-{}", handle.to_ascii_lowercase());
    let mut client = MeetingClient::connect_as(&sock, &handle, &token).await?;
    let joined = client.enter_or_create(&room).await?;
    eprintln!(
        "[participant] '{handle}' joined room '{joined}' (requested '{room}', model={model}, policy={policy:?}) — gateway {gateway_url}"
    );
    // Announce presence — this also MATERIALIZES a freshly-created room on disk so it is
    // discoverable to `meetings status` / human posts (a direct client, unlike the MCP proxy,
    // posts no automatic `joined:` line).
    let hint = match policy {
        ReplyPolicy::Mention => format!("joined: I'm {handle} (model {model}). @mention me to chat."),
        ReplyPolicy::Always => format!("joined: I'm {handle} (model {model}). I'll chime in here."),
        ReplyPolicy::Manual => format!("joined: I'm {handle} (model {model})."),
    };
    let _ = client.submit(&hint).await;

    // Maintain our OWN running transcript: `spawn_poll` streams new turns on a separate
    // connection, so `client.transcript()` (the main connection's view) does NOT include them —
    // building context from it would omit the very message we're replying to (and a strict chat
    // template like Qwen3.6's then errors "no user query"). Seed with the backlog, extend per batch.
    let mut history = client.transcript().to_vec();
    let (mut rx, _poll) = client.spawn_poll();
    while let Some(batch) = rx.recv().await {
        history.extend(batch.iter().cloned());
        if history.len() > 200 {
            history.drain(0..history.len() - 200);
        }
        for turn in batch {
            if base_handle(&turn.display_name).eq_ignore_ascii_case(&handle) {
                continue; // never reply to itself (display carries a session suffix)
            }
            if !should_reply(policy, &turn, &handle, &peers) {
                continue;
            }
            eprintln!("[participant] replying to {} …", base_handle(&turn.display_name));
            // Per-user tool capabilities: when an ACL is configured, the file/shell tools
            // offered for THIS reply are gated by the triggering messenger user's grants
            // (parsed from the `[name #id]:` prefix the bridge submits). Without an ACL,
            // the sandbox defaults to read+write (+shell only if --shell).
            let (can_read, can_write, can_shell) = match &acl_path {
                Some(path) => match sender_id_from_content(&turn.content) {
                    Some(id) => {
                        let caps = super::super::messenger_acl::Acl::load(path).caps_for(id);
                        (caps.read, caps.write, caps.shell && shell)
                    }
                    // No parseable messenger sender (e.g. a local TUI turn) → no tools.
                    None => (false, false, false),
                },
                None => (true, true, shell),
            };
            match generate(
                &gateway_url,
                &model,
                &history,
                &handle,
                persona.as_deref(),
                sandbox.as_ref(),
                can_read,
                can_write,
                can_shell,
            )
            .await
            {
                Ok(text) if !text.trim().is_empty() => {
                    if let Err(e) = client.submit(text.trim()).await {
                        eprintln!("[participant] submit failed: {e}");
                    }
                }
                Ok(_) => {}
                Err(e) => eprintln!("[participant] generate failed (staying silent): {e}"),
            }
        }
    }
    Ok(())
}

/// Max model→tool→model rounds per reply before we stop and return text. Bounds a
/// model that keeps calling tools without ever answering (weak-model loop guard).
const MAX_TOOL_ROUNDS: usize = 6;

/// Generate a reply from the local model via the gateway's OpenAI chat endpoint,
/// using the recent transcript (oldest→newest) as conversation context. When
/// `sandbox` is set the model is given file/shell tools confined to that dir and
/// its tool-calls are executed and fed back until it produces a text answer.
#[allow(clippy::too_many_arguments)]
async fn generate(
    gateway_url: &str,
    model: &str,
    transcript: &[StoredTurn],
    handle: &str,
    persona: Option<&str>,
    sandbox: Option<&super::sandbox_tools::Sandbox>,
    can_read: bool,
    can_write: bool,
    can_shell: bool,
) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
    // File/shell tools are offered only when a sandbox exists AND this user was granted the
    // capability. When nothing is granted the model runs as plain chat (no tools).
    let (read, write, shell) = match sandbox {
        Some(_) => (can_read, can_write, can_shell),
        None => (false, false, false),
    };
    let tools_on = read || write || shell;

    // Chat mechanics are always present; an operator-supplied `--persona` prepends WHO the model
    // is + any domain context (e.g. about rozum/busi) so it answers on-topic instead of generically.
    let mechanics = "Reply briefly and directly to the most recent message — actually answer the \
        question or contribute something substantive; do NOT deflect with 'how can I help' or 'what \
        would you like to explore'. Messages from others are prefixed with their name; your own are \
        not. Do NOT prefix your reply with your name.";
    let mut system = match persona {
        Some(p) if !p.trim().is_empty() => format!("{}\n\n{mechanics}", p.trim()),
        _ => format!("You are {handle}, an AI participant in a multi-person group chat. {mechanics}"),
    };
    // With tools available, tell the model which ones so it USES them instead of claiming it has
    // no filesystem access. Only advertise the capabilities this user actually has.
    if tools_on {
        let mut names = Vec::new();
        if read {
            names.push("list_files, read_file");
        }
        if write {
            names.push("write_file");
        }
        if shell {
            names.push("run_command");
        }
        // Discriminate strictly: a weak model otherwise reflexively calls a tool for every message
        // (and loops). Tools ONLY for actual file/command actions; questions get a text answer.
        system.push_str(&format!(
            "\n\nYou have a working directory with these tools: {}. Paths are relative to it. \
             Call a tool ONLY when the user asks to DO something with files or run a command \
             (create/read/change/list a file, run a command). For ordinary questions — including \
             about the project, yourself, or general chat — answer with TEXT and do NOT call any \
             tool. After a tool returns, give a short text answer; never call the same tool twice \
             in a row.",
            names.join(", ")
        ));
    }
    let messages = build_context(system, transcript, handle);
    // A strict chat template (e.g. Qwen3.6) errors without a user message — if the context held
    // only presence/own turns, there's nothing to answer; stay silent rather than send a bad call.
    if !messages.iter().any(|m| m["role"] == "user") {
        return Ok(String::new());
    }
    let mut messages = messages;

    let url = format!("{}/chat/completions", gateway_url.trim_end_matches('/'));
    let http = reqwest::Client::new();
    let tools = if tools_on {
        Some(super::sandbox_tools::Sandbox::tool_defs(read, write, shell))
    } else {
        None
    };
    // Tool mode may need to emit file contents (tool arguments count as output) — give it more
    // room than a chat one-liner.
    let max_tokens = if tools_on { 2048 } else { 400 };

    // Signature of the previous round's tool calls — if a round repeats it verbatim, the weak model
    // is stuck; stop and force a plain text answer instead of spinning into the loop-breaker.
    let mut last_sig: Option<String> = None;
    for _round in 0..MAX_TOOL_ROUNDS {
        let mut body = serde_json::json!({
            "model": model, "messages": messages, "max_tokens": max_tokens, "stream": false,
        });
        if let Some(t) = &tools {
            body["tools"] = t.clone();
        }
        let resp = http
            .post(&url)
            .json(&body)
            .timeout(Duration::from_secs(180))
            .send()
            .await?;
        if !resp.status().is_success() {
            let status = resp.status();
            return Err(
                format!("gateway {status}: {}", resp.text().await.unwrap_or_default()).into(),
            );
        }
        let json: serde_json::Value = resp.json().await?;
        let msg = &json["choices"][0]["message"];
        let content = msg["content"].as_str().unwrap_or("").to_string();
        let calls = msg["tool_calls"].as_array().filter(|c| !c.is_empty());

        // No sandbox, or the model answered instead of calling a tool → return its text.
        let (Some(sb), Some(calls)) = (sandbox, calls) else {
            return Ok(content);
        };

        // Repeat guard: identical tool call(s) to the previous round → no progress, stop looping.
        let sig = calls
            .iter()
            .map(|c| {
                format!(
                    "{}:{}",
                    c["function"]["name"].as_str().unwrap_or(""),
                    c["function"]["arguments"].as_str().unwrap_or("")
                )
            })
            .collect::<Vec<_>>()
            .join("|");
        if last_sig.as_deref() == Some(sig.as_str()) {
            break;
        }
        last_sig = Some(sig);

        // Echo the assistant's tool-call turn, then run each call in the sandbox and feed the
        // result back as a `tool` message so the next round sees it.
        messages.push(serde_json::json!({
            "role": "assistant",
            "content": content,
            "tool_calls": calls.clone(),
        }));
        for call in calls {
            let id = call["id"].as_str().unwrap_or("");
            let name = call["function"]["name"].as_str().unwrap_or("");
            let args: serde_json::Value = call["function"]["arguments"]
                .as_str()
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_else(|| serde_json::json!({}));
            let result = sb.dispatch(name, &args).await;
            eprintln!("[participant] tool {name} → {} bytes", result.len());
            messages.push(serde_json::json!({
                "role": "tool",
                "tool_call_id": id,
                "content": result,
            }));
        }
    }

    // The tool budget ran out (or the model got stuck): make ONE final tool-less call so the user
    // gets a clean text answer from the results gathered so far, not a loop-breaker artifact.
    messages.push(serde_json::json!({
        "role": "user",
        "content": "Ответь пользователю кратким текстом по результатам инструментов выше. \
                    Не вызывай инструменты.",
    }));
    let body = serde_json::json!({
        "model": model, "messages": messages, "max_tokens": max_tokens, "stream": false,
    });
    let resp = http
        .post(&url)
        .json(&body)
        .timeout(Duration::from_secs(180))
        .send()
        .await?;
    if !resp.status().is_success() {
        return Ok(String::new());
    }
    let json: serde_json::Value = resp.json().await?;
    Ok(json["choices"][0]["message"]["content"].as_str().unwrap_or("").to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn turn(name: &str, content: &str) -> StoredTurn {
        StoredTurn {
            date: "2026-06-20".into(),
            n: 1,
            participant_id: "x".into(),
            display_name: name.into(),
            content: content.into(),
            ts: 0,
            ..Default::default()
        }
    }

    #[test]
    fn mention_policy_only_on_mention() {
        assert!(should_reply(
            ReplyPolicy::Mention,
            &turn("Alice", "hey @gpt-oss what do you think?"),
            "gpt-oss",
            &[]
        ));
        assert!(!should_reply(
            ReplyPolicy::Mention,
            &turn("Alice", "just chatting"),
            "gpt-oss",
            &[]
        ));
    }

    #[test]
    fn always_skips_peer_models_no_loop() {
        let peers = vec!["qwen3.6".to_string()];
        assert!(should_reply(ReplyPolicy::Always, &turn("Alice", "hi"), "gpt-oss", &peers));
        // a peer model's message must NOT trigger a reply (no model↔model loop)
        assert!(!should_reply(ReplyPolicy::Always, &turn("qwen3.6", "hi back"), "gpt-oss", &peers));
    }

    #[test]
    fn manual_never_replies() {
        assert!(!should_reply(ReplyPolicy::Manual, &turn("Alice", "@gpt-oss hi"), "gpt-oss", &[]));
    }

    #[test]
    fn base_handle_strips_session_suffix() {
        assert_eq!(base_handle("gpt-oss · jolly-marten"), "gpt-oss");
        assert_eq!(base_handle("Sergiy · calm-tapir"), "Sergiy");
        assert_eq!(base_handle("plain"), "plain");
        // self-skip works despite the suffix
        assert!(!should_reply(
            ReplyPolicy::Always,
            &turn("gpt-oss · jolly-marten", "hi"),
            "gpt-oss",
            &["gpt-oss".into()]
        ));
    }

    #[test]
    fn build_context_dedupes_own_turns_and_drops_noise() {
        let transcript = vec![
            turn("qwen", "joined: I'm qwen"),
            turn("Sergiy", "вопрос 1"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "STUCK LOOP TEXT"),
            turn("qwen", "[redacted: old]"),
            turn("Sergiy", "вопрос 2"),
        ];
        let msgs = build_context("SYS".into(), &transcript, "qwen");
        let asst_stuck = msgs
            .iter()
            .filter(|m| m["role"] == "assistant" && m["content"] == "STUCK LOOP TEXT")
            .count();
        assert_eq!(asst_stuck, 1, "4 identical assistant turns collapse to one");
        assert!(!msgs.iter().any(|m| m["content"].as_str().unwrap_or("").contains("joined:")));
        assert!(!msgs.iter().any(|m| m["content"].as_str().unwrap_or("").contains("[redacted")));
        assert_eq!(msgs.iter().filter(|m| m["role"] == "user").count(), 2);
    }

    #[test]
    fn parses_messenger_sender_id_from_turn() {
        assert_eq!(sender_id_from_content("[Bob #42]: привет"), Some(42));
        assert_eq!(sender_id_from_content("[Сергій #1711036782]: hi"), Some(1711036782));
        // no bridge prefix → no id (local TUI turn)
        assert_eq!(sender_id_from_content("just a plain message"), None);
        assert_eq!(sender_id_from_content("[no id here]: x"), None);
    }

    #[test]
    fn reply_policy_parse_and_handle_derivation() {
        assert_eq!("mention".parse::<ReplyPolicy>().unwrap(), ReplyPolicy::Mention);
        assert!("bogus".parse::<ReplyPolicy>().is_err());
        assert_eq!(derive_handle("mlx-community:gpt-oss-20b-MXFP4-Q4"), "gpt-oss");
        assert_eq!(derive_handle("mlx-community:Qwen3.6-35B-A3B-4bit"), "qwen3.6");
    }
}
