//! Model-participant bridge: a local model joins a meeting room as a live chat
//! participant alongside humans. Spec: `docs/specs/demo-conference.md`.
//!
//! The bridge is *just a meeting client* — it reads the room transcript and
//! `meeting.submit`s replies through the existing daemon, holding no model
//! in-process: replies are generated by the local `rozum gateway`
//! (OpenAI `/v1/chat/completions`). It is never the room's writer and adds no
//! moderation/turn-taking — *when* it speaks is a per-participant policy, so the
//! daemon's single-writer / no-moderator invariants stay intact.

use std::time::Duration;

use super::room_path::meeting_sock;
use super::store::StoredTurn;
use super::tui_client::MeetingClient;

/// When the model contributes. A politeness policy of ONE participant — never a
/// room-level moderator or turn-scheduler (global meeting invariant).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReplyPolicy {
    /// Reply only when the model's handle is `@mentioned` (safe multi-model default).
    Mention,
    /// Reply to any new human message (never its own or a peer model's — loop guard).
    Always,
    /// Never reply on its own (driven externally).
    Manual,
}

impl std::str::FromStr for ReplyPolicy {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, String> {
        match s.trim().to_ascii_lowercase().as_str() {
            "mention" => Ok(Self::Mention),
            "always" => Ok(Self::Always),
            "manual" => Ok(Self::Manual),
            other => Err(format!("unknown reply-policy '{other}' (mention|always|manual)")),
        }
    }
}

/// Derive a clean roster handle from a model spec: the last path/spec segment up to
/// the size/version suffix. `mlx-community:gpt-oss-20b-MXFP4-Q4` → `gpt-oss`;
/// `mlx-community:Qwen3.6-35B-A3B-4bit` → `qwen3.6`.
pub fn derive_handle(model: &str) -> String {
    let seg = model.rsplit([':', '/']).next().unwrap_or(model);
    let mut out = String::new();
    let chars: Vec<char> = seg.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        // Stop at a `-<digit>` (size/quant suffix like `-20b`, `-35B`).
        if chars[i] == '-' && chars.get(i + 1).is_some_and(|c| c.is_ascii_digit()) {
            break;
        }
        out.push(chars[i]);
        i += 1;
    }
    let h = if out.is_empty() { seg.to_string() } else { out };
    h.to_ascii_lowercase()
}

/// The stable base of a roster display name — the daemon appends a session suffix
/// (`gpt-oss · jolly-marten` → `gpt-oss`), so compare on the base, not the full name.
pub fn base_handle(display: &str) -> &str {
    display.split('·').next().map(str::trim).unwrap_or(display)
}

/// Should the model reply to `turn`? `handle` is its own base handle (callers have
/// already excluded its own turns). `peers` are other model handles in the room, so
/// `Always` never triggers a model↔model runaway.
pub fn should_reply(policy: ReplyPolicy, turn: &StoredTurn, handle: &str, peers: &[String]) -> bool {
    match policy {
        ReplyPolicy::Manual => false,
        ReplyPolicy::Mention => turn
            .content
            .to_ascii_lowercase()
            .contains(&format!("@{}", handle.to_ascii_lowercase())),
        ReplyPolicy::Always => {
            let from = base_handle(&turn.display_name);
            !peers.iter().any(|p| p.eq_ignore_ascii_case(from))
        }
    }
}

/// Run the bridge: join `room` as `handle`, then reply via the gateway per `policy`
/// until the connection closes. Errors generating a reply are logged and swallowed —
/// a gateway hiccup must never crash the room.
#[allow(clippy::too_many_arguments)]
pub async fn run(
    model: String,
    room: String,
    handle: String,
    policy: ReplyPolicy,
    gateway_url: String,
    peers: Vec<String>,
    persona: Option<String>,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    use super::daemon::daemon_alive;
    use super::daemon_proxy::spawn_daemon;

    let sock = meeting_sock();
    if !daemon_alive(&sock).await {
        spawn_daemon().await;
    }
    // Stable identity per handle → ONE roster participant across restarts.
    let token = format!("model-participant-{}", handle.to_ascii_lowercase());
    let mut client = MeetingClient::connect_as(&sock, &handle, &token).await?;
    let joined = client.enter_or_create(&room).await?;
    eprintln!(
        "[participant] '{handle}' joined room '{joined}' (requested '{room}', model={model}, policy={policy:?}) — gateway {gateway_url}"
    );
    // Announce presence — this also MATERIALIZES a freshly-created room on disk so it is
    // discoverable to `meetings status` / human posts (a direct client, unlike the MCP proxy,
    // posts no automatic `joined:` line).
    let hint = match policy {
        ReplyPolicy::Mention => format!("joined: I'm {handle} (model {model}). @mention me to chat."),
        ReplyPolicy::Always => format!("joined: I'm {handle} (model {model}). I'll chime in here."),
        ReplyPolicy::Manual => format!("joined: I'm {handle} (model {model})."),
    };
    let _ = client.submit(&hint).await;

    // Maintain our OWN running transcript: `spawn_poll` streams new turns on a separate
    // connection, so `client.transcript()` (the main connection's view) does NOT include them —
    // building context from it would omit the very message we're replying to (and a strict chat
    // template like Qwen3.6's then errors "no user query"). Seed with the backlog, extend per batch.
    let mut history = client.transcript().to_vec();
    let (mut rx, _poll) = client.spawn_poll();
    while let Some(batch) = rx.recv().await {
        history.extend(batch.iter().cloned());
        if history.len() > 200 {
            history.drain(0..history.len() - 200);
        }
        for turn in batch {
            if base_handle(&turn.display_name).eq_ignore_ascii_case(&handle) {
                continue; // never reply to itself (display carries a session suffix)
            }
            if !should_reply(policy, &turn, &handle, &peers) {
                continue;
            }
            eprintln!("[participant] replying to {} …", base_handle(&turn.display_name));
            match generate(&gateway_url, &model, &history, &handle, persona.as_deref()).await {
                Ok(text) if !text.trim().is_empty() => {
                    if let Err(e) = client.submit(text.trim()).await {
                        eprintln!("[participant] submit failed: {e}");
                    }
                }
                Ok(_) => {}
                Err(e) => eprintln!("[participant] generate failed (staying silent): {e}"),
            }
        }
    }
    Ok(())
}

/// Generate a reply from the local model via the gateway's OpenAI chat endpoint,
/// using the recent transcript (oldest→newest) as conversation context.
async fn generate(
    gateway_url: &str,
    model: &str,
    transcript: &[StoredTurn],
    handle: &str,
    persona: Option<&str>,
) -> Result<String, Box<dyn std::error::Error + Send + Sync>> {
    // Chat mechanics are always present; an operator-supplied `--persona` prepends WHO the model
    // is + any domain context (e.g. about rozum/busi) so it answers on-topic instead of generically.
    let mechanics = "Reply briefly and directly to the most recent message — actually answer the \
        question or contribute something substantive; do NOT deflect with 'how can I help' or 'what \
        would you like to explore'. Messages from others are prefixed with their name; your own are \
        not. Do NOT prefix your reply with your name.";
    let system = match persona {
        Some(p) if !p.trim().is_empty() => format!("{}\n\n{mechanics}", p.trim()),
        _ => format!("You are {handle}, an AI participant in a multi-person group chat. {mechanics}"),
    };
    let mut messages = vec![serde_json::json!({ "role": "system", "content": system })];
    let start = transcript.len().saturating_sub(24);
    for t in &transcript[start..] {
        // Presence lines (`joined:`/`left:`) are roster noise — the model's own join announcement
        // in its context primes a terse social reply; drop them so it sees only real conversation.
        let c = t.content.trim_start();
        if c.starts_with("joined:") || c.starts_with("left:") {
            continue;
        }
        let who = base_handle(&t.display_name);
        if who.eq_ignore_ascii_case(handle) {
            messages.push(serde_json::json!({ "role": "assistant", "content": t.content }));
        } else {
            messages.push(serde_json::json!({
                "role": "user",
                "content": format!("{}: {}", who, t.content),
            }));
        }
    }
    // A strict chat template (e.g. Qwen3.6) errors without a user message — if the context held
    // only presence/own turns, there's nothing to answer; stay silent rather than send a bad call.
    if !messages.iter().any(|m| m["role"] == "user") {
        return Ok(String::new());
    }
    let body = serde_json::json!({
        "model": model, "messages": messages, "max_tokens": 400, "stream": false,
    });
    let url = format!("{}/chat/completions", gateway_url.trim_end_matches('/'));
    let resp = reqwest::Client::new()
        .post(&url)
        .json(&body)
        .timeout(Duration::from_secs(180))
        .send()
        .await?;
    if !resp.status().is_success() {
        let status = resp.status();
        return Err(format!("gateway {status}: {}", resp.text().await.unwrap_or_default()).into());
    }
    let json: serde_json::Value = resp.json().await?;
    Ok(json["choices"][0]["message"]["content"]
        .as_str()
        .unwrap_or("")
        .to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn turn(name: &str, content: &str) -> StoredTurn {
        StoredTurn {
            date: "2026-06-20".into(),
            n: 1,
            participant_id: "x".into(),
            display_name: name.into(),
            content: content.into(),
            ts: 0,
            ..Default::default()
        }
    }

    #[test]
    fn mention_policy_only_on_mention() {
        assert!(should_reply(
            ReplyPolicy::Mention,
            &turn("Alice", "hey @gpt-oss what do you think?"),
            "gpt-oss",
            &[]
        ));
        assert!(!should_reply(
            ReplyPolicy::Mention,
            &turn("Alice", "just chatting"),
            "gpt-oss",
            &[]
        ));
    }

    #[test]
    fn always_skips_peer_models_no_loop() {
        let peers = vec!["qwen3.6".to_string()];
        assert!(should_reply(ReplyPolicy::Always, &turn("Alice", "hi"), "gpt-oss", &peers));
        // a peer model's message must NOT trigger a reply (no model↔model loop)
        assert!(!should_reply(ReplyPolicy::Always, &turn("qwen3.6", "hi back"), "gpt-oss", &peers));
    }

    #[test]
    fn manual_never_replies() {
        assert!(!should_reply(ReplyPolicy::Manual, &turn("Alice", "@gpt-oss hi"), "gpt-oss", &[]));
    }

    #[test]
    fn base_handle_strips_session_suffix() {
        assert_eq!(base_handle("gpt-oss · jolly-marten"), "gpt-oss");
        assert_eq!(base_handle("Sergiy · calm-tapir"), "Sergiy");
        assert_eq!(base_handle("plain"), "plain");
        // self-skip works despite the suffix
        assert!(!should_reply(
            ReplyPolicy::Always,
            &turn("gpt-oss · jolly-marten", "hi"),
            "gpt-oss",
            &["gpt-oss".into()]
        ));
    }

    #[test]
    fn reply_policy_parse_and_handle_derivation() {
        assert_eq!("mention".parse::<ReplyPolicy>().unwrap(), ReplyPolicy::Mention);
        assert!("bogus".parse::<ReplyPolicy>().is_err());
        assert_eq!(derive_handle("mlx-community:gpt-oss-20b-MXFP4-Q4"), "gpt-oss");
        assert_eq!(derive_handle("mlx-community:Qwen3.6-35B-A3B-4bit"), "qwen3.6");
    }
}
