// Generated by scalascript frontend/tui (ratatui backend) — slice 5 (fetch-binding).
// App: ScalaScript TUI
#![allow(unused_imports, unused_variables, dead_code)]
use std::collections::HashMap;
use std::io;
use std::time::Duration;
use ratatui::backend::{TestBackend, CrosstermBackend};
use ratatui::{Terminal, Frame};
use ratatui::layout::{Layout, Constraint, Rect};
use ratatui::widgets::{Paragraph, Block, Borders, Table, Row};
use ratatui::style::{Style, Modifier, Color};
use ratatui::buffer::Buffer;
use ratatui::crossterm::event::{self, Event, KeyCode, KeyEventKind};
use ratatui::crossterm::terminal::{enable_raw_mode, disable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen};
use ratatui::crossterm::execute;

#[derive(Clone, PartialEq, Debug)]
enum Value { S(String), I(i64), B(bool) }
impl Value {
    fn display(&self) -> String {
        match self { Value::S(s) => s.clone(), Value::I(n) => n.to_string(), Value::B(b) => b.to_string() }
    }
    fn truthy(&self) -> bool {
        match self { Value::B(b) => *b, Value::S(s) => !s.is_empty(), Value::I(n) => *n != 0 }
    }
}
fn sig(signals: &HashMap<String, Value>, id: &str) -> String {
    signals.get(id).map(|v| v.display()).unwrap_or_default()
}
fn sig_int(signals: &HashMap<String, Value>, id: &str) -> i64 {
    match signals.get(id) { Some(Value::I(n)) => *n, Some(Value::S(s)) => s.parse().unwrap_or(0), Some(Value::B(b)) => if *b { 1 } else { 0 }, None => 0 }
}
fn sig_truthy(signals: &HashMap<String, Value>, id: &str) -> bool {
    signals.get(id).map(|v| v.truthy()).unwrap_or(false)
}
fn toggle_text(signals: &HashMap<String, Value>, id: &str, label: &str) -> String {
    let box_str = if sig_truthy(signals, id) { "[x]" } else { "[ ]" };
    if label.is_empty() { box_str.to_string() } else { format!("{} {}", box_str, label) }
}
fn text_input_display(signals: &HashMap<String, Value>, id: &str, placeholder: &str, secure: bool) -> String {
    let v = sig(signals, id);
    if v.is_empty() { placeholder.to_string() }
    else if secure { "*".repeat(v.chars().count()) }
    else { v }
}

fn initial_signals() -> HashMap<String, Value> {
    let mut m: HashMap<String, Value> = HashMap::new();
    m.insert("meetingsUrl".to_string(), Value::S("http://127.0.0.1:8401/rooms/rozum/messages/today".to_string()));
    m.insert("meetingsDraft".to_string(), Value::S("".to_string()));
    m.insert("meetingsRefresh".to_string(), Value::I(0));
    m.insert("meetingsNewRoom".to_string(), Value::S("".to_string()));
    m
}

fn fetch_text(url: &str, headers: &[(String, String)]) -> Option<String> {
    let mut req = ureq::get(url);
    for (name, value) in headers { req = req.set(name, value); }
    match req.call() { Ok(resp) => resp.into_string().ok(), Err(_) => None }
}
fn load_fetch(signals: &mut HashMap<String, Value>, id: &str, url: &str, headers: &[(String, String)]) {
    // An empty URL is a picker with nothing selected: make NO request and keep whatever
    // was already there, rather than GET "" and blank a populated table.
    if url.is_empty() { return; }
    if let Some(body) = fetch_text(url, headers) { signals.insert(id.to_string(), Value::S(body)); }
}
fn bootstrap(signals: &mut HashMap<String, Value>) {
    {
        let mut __h: Vec<(String, String)> = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } load_fetch(signals, "meetingsRooms", "http://127.0.0.1:8401/rooms", &__h);
    }
    {
        let mut __h: Vec<(String, String)> = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } load_fetch(signals, "meetingsDays", "http://127.0.0.1:8401/rooms/rozum/days", &__h);
    }
    {
        let mut __h: Vec<(String, String)> = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } load_fetch(signals, "meetingsTranscript", &sig(signals, "meetingsUrl"), &__h);
    }
}
fn initial_fetch_ticks(signals: &HashMap<String, Value>) -> HashMap<String, String> {
    let mut observed = HashMap::new();
    observed.insert("meetingsRooms".to_string(), format!("{}", sig_int(signals, "meetingsRefresh")));
    observed.insert("meetingsDays".to_string(), format!("{}", sig_int(signals, "meetingsRefresh")));
    observed.insert("meetingsTranscript".to_string(), format!("{} {}", sig_int(signals, "meetingsRefresh"), sig(signals, "meetingsUrl")));
    observed
}
fn refresh_fetches(signals: &mut HashMap<String, Value>, observed: &mut HashMap<String, String>) {
    {
        let current = format!("{}", sig_int(signals, "meetingsRefresh"));
        if observed.get("meetingsRooms") != Some(&current) {
            {
                let mut __h: Vec<(String, String)> = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } load_fetch(signals, "meetingsRooms", "http://127.0.0.1:8401/rooms", &__h);
            }
            observed.insert("meetingsRooms".to_string(), current);
        }
    }
    {
        let current = format!("{}", sig_int(signals, "meetingsRefresh"));
        if observed.get("meetingsDays") != Some(&current) {
            {
                let mut __h: Vec<(String, String)> = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } load_fetch(signals, "meetingsDays", "http://127.0.0.1:8401/rooms/rozum/days", &__h);
            }
            observed.insert("meetingsDays".to_string(), current);
        }
    }
    {
        let current = format!("{} {}", sig_int(signals, "meetingsRefresh"), sig(signals, "meetingsUrl"));
        if observed.get("meetingsTranscript") != Some(&current) {
            {
                let mut __h: Vec<(String, String)> = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } load_fetch(signals, "meetingsTranscript", &sig(signals, "meetingsUrl"), &__h);
            }
            observed.insert("meetingsTranscript".to_string(), current);
        }
    }
}
fn send_action(signals: &mut HashMap<String, Value>, method: &str, url: &str,
                body_id: &str, tick_id: &str, clear_body: bool, headers: &[(String, String)]) {
    if url.is_empty() { return; }
    let body = sig(signals, body_id);
    let mut req = ureq::request(method, url);
    req = req.set("Content-Type", "application/json");
    for (name, value) in headers { req = req.set(name, value); }
    if req.send_string(&body).is_ok() {
        let cur = match signals.get(tick_id) { Some(Value::I(n)) => *n, _ => 0 };
        signals.insert(tick_id.to_string(), Value::I(cur + 1));
        if clear_body { signals.insert(body_id.to_string(), Value::S(String::new())); }
    }
}
fn bump_interval_ticks(signals: &mut HashMap<String, Value>, last: &mut HashMap<String, std::time::Instant>) {
    let now = std::time::Instant::now();
    { let __e = last.entry("meetingsRefresh".to_string()).or_insert(now); if now.duration_since(*__e).as_millis() >= 3000u128 { *__e = now; let __c = match signals.get("meetingsRefresh") { Some(Value::I(n)) => *n, _ => 0 }; signals.insert("meetingsRefresh".to_string(), Value::I(__c + 1)); } }
}
fn json_field(row: &serde_json::Value, path: &str) -> String {
    let mut cur = row;
    for part in path.split('.') { cur = match cur.get(part) { Some(x) => x, None => return String::new() }; }
    match cur {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Null => String::new(),
        other => other.to_string(),
    }
}
fn row_identity(row: &serde_json::Value, row_key_path: &str) -> Result<String, String> {
    if row_key_path.is_empty() || row_key_path.split('.').any(|part| part.is_empty()) {
        return Err("rowKeyPath must be a non-empty dotted path".to_string());
    }
    let mut cur = row;
    for part in row_key_path.split('.') {
        cur = cur.get(part).ok_or_else(|| format!("missing row key at {}", row_key_path))?;
    }
    match cur {
        serde_json::Value::String(value) if !value.is_empty() => Ok(format!("string:{}", value)),
        serde_json::Value::Number(value) if value.as_i64().is_some() || value.as_u64().is_some() => Ok(format!("int:{}", value)),
        _ => Err(format!("row key at {} must be a non-empty String or integral number", row_key_path)),
    }
}
fn fetch_rows(json: &str, rows_path: &str, row_key_path: &str, field_paths: &[&str]) -> Result<Vec<Vec<String>>, String> {
    use std::collections::HashSet;
    let v: serde_json::Value = serde_json::from_str(json).map_err(|_| "table response is not JSON".to_string())?;
    let arr_val: &serde_json::Value = if rows_path.is_empty() {
        ["data", "rows", "items", "results"].iter().find_map(|k| v.get(k)).unwrap_or(&v)
    } else {
        let mut cur = &v;
        for part in rows_path.split('.') { cur = cur.get(part).ok_or_else(|| format!("missing rowsPath {}", rows_path))?; }
        cur
    };
    let arr = arr_val.as_array().ok_or_else(|| "table rows are not an array".to_string())?;
    let mut seen = HashSet::new();
    let mut result = Vec::with_capacity(arr.len());
    for (index, row) in arr.iter().enumerate() {
        let identity = row_identity(row, row_key_path).map_err(|e| format!("row {}: {}", index, e))?;
        if !seen.insert(identity.clone()) { return Err(format!("duplicate row key {}", identity)); }
        result.push(field_paths.iter().map(|fp| json_field(row, fp)).collect());
    }
    Ok(result)
}
fn rows_at<'a>(json: &'a serde_json::Value, rows_path: &str) -> Option<&'a Vec<serde_json::Value>> {
    let mut cur = json;
    if !rows_path.is_empty() {
        for part in rows_path.split('.') { cur = cur.get(part)?; }
    } else if !cur.is_array() {
        for key in ["data", "rows", "items", "results"] {
            if let Some(v) = cur.get(key) { cur = v; break; }
        }
    }
    cur.as_array()
}
fn row_count(json: &str, rows_path: &str) -> usize {
    match serde_json::from_str::<serde_json::Value>(json) {
        Ok(v) => rows_at(&v, rows_path).map(|r| r.len()).unwrap_or(0),
        Err(_) => 0,
    }
}
fn row_field(json: &str, rows_path: &str, index: i64, field: &str) -> Option<String> {
    if index < 0 { return None; }
    let v = serde_json::from_str::<serde_json::Value>(json).ok()?;
    let rows = rows_at(&v, rows_path)?;
    let row = rows.get(index as usize)?;
    Some(json_field(row, field))
}

fn resolve_credential(kind: &str, source: &str, scheme: &str) -> Option<String> {
    let secret = match kind {
        "env" => std::env::var(source).ok(),
        "file" => {
            let path = if let Some(rest) = source.strip_prefix("~/") {
                match std::env::var("HOME") { Ok(h) => format!("{}/{}", h, rest), Err(_) => source.to_string() }
            } else { source.to_string() };
            std::fs::read_to_string(path).ok().map(|s| s.trim().to_string())
        }
        "literal" => Some(source.to_string()),
        _ => None,
    }?;
    if secret.is_empty() { return None; }
    Some(format!("{} {}", scheme, secret))
}


const FOCUS_COUNT: usize = 7;
fn focus_mark(focus: usize, idx: usize) -> &'static str { if focus == idx { "> " } else { "  " } }
fn is_text_input(focus: usize) -> bool { matches!(focus, 2 | 4) }
fn is_table(focus: usize) -> bool { matches!(focus, 0 | 1) }
fn move_row(focus: usize, signals: &mut HashMap<String, Value>, delta: i64) {
    match focus {
        0 => { let __n = row_count(&sig(signals, "meetingsRooms"), "entries") as i64; let __cur = match signals.get("meetingsRooms__row") { Some(Value::I(n)) => *n, _ => 0 }; let __next = if __n == 0 { 0 } else { (__cur + delta).clamp(0, __n - 1) }; signals.insert("meetingsRooms__row".to_string(), Value::I(__next)); }
        1 => { let __n = row_count(&sig(signals, "meetingsDays"), "entries") as i64; let __cur = match signals.get("meetingsDays__row") { Some(Value::I(n)) => *n, _ => 0 }; let __next = if __n == 0 { 0 } else { (__cur + delta).clamp(0, __n - 1) }; signals.insert("meetingsDays__row".to_string(), Value::I(__next)); }
        _ => {}
    }
}

fn activate(focus: usize, signals: &mut HashMap<String, Value>) {
    match focus {
        0 => { let __i = match signals.get("meetingsRooms__row") { Some(Value::I(n)) => *n, _ => 0 }; if let Some(__v) = row_field(&sig(signals, "meetingsRooms"), "entries", __i, "url") { signals.insert("meetingsUrl".to_string(), Value::S(__v)); } }
        1 => { let __i = match signals.get("meetingsDays__row") { Some(Value::I(n)) => *n, _ => 0 }; if let Some(__v) = row_field(&sig(signals, "meetingsDays"), "entries", __i, "url") { signals.insert("meetingsUrl".to_string(), Value::S(__v)); } }
        3 => { let mut __h = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } send_action(signals, "POST", "http://127.0.0.1:8401/rooms/rozum/messages", "meetingsDraft", "meetingsRefresh", true, &__h); }
        5 => { let mut __h = Vec::new(); if let Some(__a) = resolve_credential("env", "ROZUM_MEETING_TOKEN", "Bearer") { __h.push(("Authorization".to_string(), __a)); } send_action(signals, "POST", "http://127.0.0.1:8401/rooms", "meetingsNewRoom", "meetingsRefresh", true, &__h); }
        6 => { let cur = match signals.get("meetingsRefresh") { Some(Value::I(n)) => *n, _ => 0 }; signals.insert("meetingsRefresh".to_string(), Value::I(cur + 1)); }
        _ => {}
    }
}

fn type_char(focus: usize, signals: &mut HashMap<String, Value>, c: char) {
    match focus {
        2 => { let mut s = sig(signals, "meetingsDraft"); s.push(c); signals.insert("meetingsDraft".to_string(), Value::S(s)); }
        4 => { let mut s = sig(signals, "meetingsNewRoom"); s.push(c); signals.insert("meetingsNewRoom".to_string(), Value::S(s)); }
        _ => {}
    }
}

fn backspace(focus: usize, signals: &mut HashMap<String, Value>) {
    match focus {
        2 => { let mut s = sig(signals, "meetingsDraft"); s.pop(); signals.insert("meetingsDraft".to_string(), Value::S(s)); }
        4 => { let mut s = sig(signals, "meetingsNewRoom"); s.pop(); signals.insert("meetingsNewRoom".to_string(), Value::S(s)); }
        _ => {}
    }
}

fn handle_key(code: KeyCode, signals: &mut HashMap<String, Value>, focus: &mut usize) -> bool {
    match code {
        KeyCode::Esc => return true,
        // Arrows belong to the FOCUSED WIDGET when that widget is a table; Tab is the
        // canonical focus key and always moves focus. With no selectable table `is_table`
        // is a constant `false`, so this is the previous behaviour exactly.
        KeyCode::Down if is_table(*focus) => move_row(*focus, signals, 1),
        KeyCode::Up   if is_table(*focus) => move_row(*focus, signals, -1),
        KeyCode::Tab | KeyCode::Down => { if FOCUS_COUNT > 0 { *focus = (*focus + 1) % FOCUS_COUNT; } }
        KeyCode::BackTab | KeyCode::Up => { if FOCUS_COUNT > 0 { *focus = (*focus + FOCUS_COUNT - 1) % FOCUS_COUNT; } }
        KeyCode::Enter => activate(*focus, signals),
        KeyCode::Backspace if is_text_input(*focus) => backspace(*focus, signals),
        KeyCode::Char(c) => {
            if is_text_input(*focus) { type_char(*focus, signals, c); }
            else if c == ' ' { activate(*focus, signals); }
            else if c == 'q' { return true; }
        }
        _ => {}
    }
    false
}

fn render_root(frame: &mut Frame, area: Rect, signals: &HashMap<String, Value>, focus: usize) {
    let chunks0 = Layout::horizontal([Constraint::Ratio(1, 2), Constraint::Ratio(1, 2)]).split(area);
    let chunks1 = Layout::vertical([Constraint::Length(1), Constraint::Min(3), Constraint::Min(3), Constraint::Length(2), Constraint::Length(1), Constraint::Length(2), Constraint::Length(1), Constraint::Length(1)]).split(chunks0[0]);
    frame.render_widget(Paragraph::new("rozum"), chunks1[0]);
    { let __json = sig(signals, "meetingsRooms"); let __rows = fetch_rows(&__json, "entries", "name", &["name", "last", "mentions"]).expect("invalid DataTable row identity"); let __trows: Vec<Row> = __rows.iter().map(|r| Row::new(r.iter().cloned().collect::<Vec<String>>())).collect(); let __t = Table::new(__trows, [Constraint::Ratio(1, 3), Constraint::Ratio(1, 3), Constraint::Ratio(1, 3)]).header(Row::new(vec!["Room", "Last", "@you"])).row_highlight_style(Style::default().add_modifier(Modifier::REVERSED)); let __sel = if __rows.is_empty() { 0usize } else { (match signals.get("meetingsRooms__row") { Some(Value::I(n)) => *n, _ => 0 }).clamp(0, __rows.len() as i64 - 1) as usize }; let mut __st = ratatui::widgets::TableState::default(); if !__rows.is_empty() && focus == 0 { __st.select(Some(__sel)); } frame.render_stateful_widget(__t, chunks1[1], &mut __st); }
    { let __json = sig(signals, "meetingsDays"); let __rows = fetch_rows(&__json, "entries", "date", &["date", "count"]).expect("invalid DataTable row identity"); let __trows: Vec<Row> = __rows.iter().map(|r| Row::new(r.iter().cloned().collect::<Vec<String>>())).collect(); let __t = Table::new(__trows, [Constraint::Ratio(1, 2), Constraint::Ratio(1, 2)]).header(Row::new(vec!["Day", "#"])).row_highlight_style(Style::default().add_modifier(Modifier::REVERSED)); let __sel = if __rows.is_empty() { 0usize } else { (match signals.get("meetingsDays__row") { Some(Value::I(n)) => *n, _ => 0 }).clamp(0, __rows.len() as i64 - 1) as usize }; let mut __st = ratatui::widgets::TableState::default(); if !__rows.is_empty() && focus == 1 { __st.select(Some(__sel)); } frame.render_stateful_widget(__t, chunks1[2], &mut __st); }
    let chunks2 = Layout::vertical([Constraint::Length(1), Constraint::Length(1)]).split(chunks1[3]);
    frame.render_widget(Paragraph::new("message"), chunks2[0]);
    frame.render_widget(Paragraph::new(format!("{}{}", focus_mark(focus, 2), text_input_display(signals, "meetingsDraft", "message", false))).style(if focus == 2 { Style::default().add_modifier(Modifier::REVERSED) } else { Style::default() }), chunks2[1]);
    frame.render_widget(Paragraph::new(format!("{}[{}]", focus_mark(focus, 3), "send")).style(if focus == 3 { Style::default().add_modifier(Modifier::REVERSED) } else { Style::default() }), chunks1[4]);
    let chunks3 = Layout::vertical([Constraint::Length(1), Constraint::Length(1)]).split(chunks1[5]);
    frame.render_widget(Paragraph::new("new room topic"), chunks3[0]);
    frame.render_widget(Paragraph::new(format!("{}{}", focus_mark(focus, 4), text_input_display(signals, "meetingsNewRoom", "new room topic", false))).style(if focus == 4 { Style::default().add_modifier(Modifier::REVERSED) } else { Style::default() }), chunks3[1]);
    frame.render_widget(Paragraph::new(format!("{}[{}]", focus_mark(focus, 5), "create room")).style(if focus == 5 { Style::default().add_modifier(Modifier::REVERSED) } else { Style::default() }), chunks1[6]);
    frame.render_widget(Paragraph::new(format!("{}[{}]", focus_mark(focus, 6), "refresh")).style(if focus == 6 { Style::default().add_modifier(Modifier::REVERSED) } else { Style::default() }), chunks1[7]);
    { let __json = sig(signals, "meetingsTranscript"); let __rows = fetch_rows(&__json, "messages", "ts", &["time", "display_name", "badge", "content"]).expect("invalid DataTable row identity"); let __trows: Vec<Row> = __rows.iter().map(|r| Row::new(r.iter().cloned().collect::<Vec<String>>())).collect(); let __t = Table::new(__trows, [Constraint::Ratio(1, 4), Constraint::Ratio(1, 4), Constraint::Ratio(1, 4), Constraint::Ratio(1, 4)]).header(Row::new(vec!["Time", "Who", "", "Message"])); frame.render_widget(__t, chunks0[1]); }
}

fn buffer_to_lines(buf: &Buffer) -> String {
    let area = buf.area;
    let mut out = String::new();
    for y in 0..area.height {
        let mut line = String::new();
        for x in 0..area.width {
            line.push_str(buf[(x, y)].symbol());
        }
        out.push_str(line.trim_end());
        out.push('\n');
    }
    out
}

fn render_to_string(width: u16, height: u16, signals: &HashMap<String, Value>, focus: usize) -> String {
    let mut terminal = Terminal::new(TestBackend::new(width, height)).expect("terminal init");
    terminal.draw(|f| { let area = f.area(); render_root(f, area, signals, focus); }).expect("draw");
    buffer_to_lines(terminal.backend().buffer())
}

fn run_interactive() -> io::Result<()> {
    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let mut terminal = Terminal::new(CrosstermBackend::new(stdout))?;
    let mut signals = initial_signals();
    bootstrap(&mut signals);
    let mut observed_fetch_ticks = initial_fetch_ticks(&signals);
    let mut last_interval: HashMap<String, std::time::Instant> = HashMap::new();
    let mut focus: usize = 0;
    let result = (|| -> io::Result<()> {
        loop {
            // Advance auto-polling ticks BEFORE the refresh, so a due tick is acted on in
            // the frame that notices it rather than the next one.
            bump_interval_ticks(&mut signals, &mut last_interval);
            refresh_fetches(&mut signals, &mut observed_fetch_ticks);
            terminal.draw(|f| { let area = f.area(); render_root(f, area, &signals, focus); })?;
            if event::poll(Duration::from_millis(100))? {
                if let Event::Key(key) = event::read()? {
                    if key.kind == KeyEventKind::Press {
                        if handle_key(key.code, &mut signals, &mut focus) { break; }
                    }
                }
            }
        }
        Ok(())
    })();
    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    result
}

fn main() {
    if std::env::var("SSC_TUI_SNAPSHOT").is_ok() {
        let mut signals = initial_signals();
        bootstrap(&mut signals);
        print!("{}", render_to_string(80, 24, &signals, 0));
    } else {
        let _ = run_interactive();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn datatable_row_identity_contract() {
        let fields = ["id"];
        assert!(fetch_rows(r#"{"data":[{"id":1},{"id":"1"}]}"#, "data", "id", &fields).is_ok());
        for invalid in [
            r#"{"data":[{}]}"#,
            r#"{"data":[{"id":""}]}"#,
            r#"{"data":[{"id":{"nested":1}}]}"#,
            r#"{"data":[{"id":1},{"id":1}]}"#,
            r#"{"data":[[]]}"#,
        ] {
            assert!(fetch_rows(invalid, "data", "id", &fields).is_err(), "accepted {}", invalid);
        }
    }
    #[test]
    fn reactive_rerender() {
        let mut signals = initial_signals();
        let before = render_to_string(80, 24, &signals, 0);
        signals.insert("meetingsUrl".to_string(), Value::S("SSC_RERENDER_SENTINEL".to_string()));
        let after = render_to_string(80, 24, &signals, 0);
        assert_ne!(before, after, "signal change did not re-render");
        assert!(after.contains("SSC_RERENDER_SENTINEL"), "new value not rendered");
    }
    #[test]
    fn event_handlers_run() {
        let mut signals = initial_signals();
        let before = signals.clone();
        activate(0, &mut signals);
        assert_ne!(before, signals, "activate did not mutate the store");
    }
    #[test]
    fn text_input_typing() {
        let mut signals = initial_signals();
        type_char(2, &mut signals, 'X');
        assert!(sig(&signals, "meetingsDraft").contains('X'), "typed char not in signal");
    }
    #[test]
    fn tab_moves_focus() {
        let mut signals = initial_signals();
        let mut focus = 0usize;
        handle_key(KeyCode::Tab, &mut signals, &mut focus);
        assert_eq!(focus, 1);
    }
}
