#!/usr/bin/env bash
#
# regen-uniml-md.sh — regenerate the vendored `crates/uniml-md` crate from a scalascript
# checkout (docs/specs/syntactic-rag.md).
#
# The crate is the `ssc-tools emit-rust` output of uniML core+markup+markdown, COMMITTED as
# generated Rust so rozum's own build stays hermetic: no ssc, no JVM, no network — that is the
# operator's "path A" decision, and this script is the only place the ssc toolchain is ever
# invoked. Regeneration is an explicit dev action, run when scalascript's uniml/ moves.
#
# Usage:
#   SCALASCRIPT_DIR=../scalascript scripts/regen-uniml-md.sh
#
# SCALASCRIPT_DIR defaults to ../scalascript. On the machine this was first built on the
# checkout lives at ../scalascript-wt-uniml-dialect-modules (a worktree of the same repo whose
# uniml/ state equals origin/main after the 2026-08-30 merge).
#
# The merge list below reconstructs the exact single-file corpus the ssc→Rust hardening
# campaign compiled clean (155→0 real cargo errors): every uniml file that the markdown
# dialect transitively needs, concatenated with package/import lines stripped (the merged file
# is one compilation unit, so intra-uniml imports are meaningless there) and the one external
# alphabet reference rewritten to the merged-in copy. Order matters only for readability; ssc
# resolves across the whole unit.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCALASCRIPT_DIR="${SCALASCRIPT_DIR:-$ROOT/../scalascript}"
CRATE="$ROOT/crates/uniml-md"

test -x "$SCALASCRIPT_DIR/bin/ssc-tools" || {
  echo "regen-uniml-md: no bin/ssc-tools under SCALASCRIPT_DIR=$SCALASCRIPT_DIR" >&2
  echo "  (build it there first: bash install.sh --dev)" >&2
  exit 2
}
SRC_SHA="$(git -C "$SCALASCRIPT_DIR" rev-parse HEAD)"

FILES=(
  "alphabet/src/Alphabet.scala"
  "uniml/core/src/main/scala/scalascript/uniml/Diagnostics.scala"
  "uniml/core/src/main/scala/scalascript/uniml/Source.scala"
  "uniml/core/src/main/scala/scalascript/uniml/Tree.scala"
  "uniml/core/src/main/scala/scalascript/uniml/Processor.scala"
  "uniml/core/src/main/scala/scalascript/uniml/Dialect.scala"
  "uniml/core/src/main/scala/scalascript/uniml/dialect/Literal.scala"
  "uniml/core/src/main/scala/scalascript/uniml/TreeVm.scala"
  "uniml/core/src/main/scala/scalascript/uniml/UniAlphabet.scala"
  "uniml/core/src/main/scala/scalascript/uniml/UniML.scala"
  "uniml/markdown/src/main/scala/scalascript/uniml/dialect/markdown/generated/MarkdownEntitiesGenerated.scala"
  "uniml/markdown/src/main/scala/scalascript/uniml/dialect/markdown/MarkdownValue.scala"
  "uniml/markdown/src/main/scala/scalascript/uniml/dialect/markdown/MarkdownInlines.scala"
  "uniml/markdown/src/main/scala/scalascript/uniml/dialect/markdown/MarkdownBlocks.scala"
  "uniml/markdown/src/main/scala/scalascript/uniml/dialect/markdown/MarkdownLexer.scala"
  "uniml/markdown/src/main/scala/scalascript/uniml/dialect/markdown/MarkdownProjection.scala"
  "uniml/markdown/src/main/scala/scalascript/uniml/dialect/markdown/MarkdownDialect.scala"
)

WORK="$(mktemp -d "${TMPDIR:-/tmp}/regen-uniml-md.XXXXXX")"
trap 'rm -rf "$WORK"' EXIT
MERGED="$WORK/merged.scala"

: > "$MERGED"
for f in "${FILES[@]}"; do
  test -f "$SCALASCRIPT_DIR/$f" || { echo "regen-uniml-md: missing $SCALASCRIPT_DIR/$f" >&2; exit 2; }
  grep -v -E '^\s*package\s|^\s*import\s+scalascript\.uniml\b|^\s*import\s+scalascript\.markup\b|^\s*import\s+MarkdownInlines\b|^\s*import\s+scalascript\.uniml\.dialect\.markdown\.generated\b' \
    "$SCALASCRIPT_DIR/$f" \
    | sed 's/scalascript\.alphabet\.Alphabet\./Alphabet./g' \
    >> "$MERGED"
  echo "" >> "$MERGED"
done
echo "regen-uniml-md: merged $(wc -l < "$MERGED" | tr -d ' ') lines from ${#FILES[@]} files (scalascript $SRC_SHA)"

SSC_NO_BUILD_CHECK=1 "$SCALASCRIPT_DIR/bin/ssc-tools" emit-rust "$MERGED" -o "$WORK/out"
test -f "$WORK/out/src/generated/ssc_program.rs" || {
  echo "regen-uniml-md: emit-rust produced no src/generated/ssc_program.rs" >&2; exit 2; }

# Rewrite the crate: generated sources verbatim, our own Cargo.toml (the emitted one carries
# [profile.*] sections a workspace member may not have, and the ssc_program name), and a
# provenance + lint header prepended to lib.rs. `#![allow]` inner attributes are legal after
# the leading `//!` doc lines only if they come first, so the header goes at byte 0.
rm -rf "$CRATE/src"
mkdir -p "$CRATE"
cp -R "$WORK/out/src" "$CRATE/src"

cat > "$CRATE/Cargo.toml" <<EOF
# GENERATED CRATE — do not edit by hand. scripts/regen-uniml-md.sh rewrites all of it.
# Source: scalascript uniml core+markup+markdown at $SRC_SHA, via ssc-tools emit-rust.
[package]
name = "uniml-md"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "uniml_md"
path = "src/lib.rs"
EOF

LIB="$CRATE/src/lib.rs"
{
  echo "// GENERATED by scripts/regen-uniml-md.sh — do not edit."
  echo "// Source: scalascript uniml core+markup+markdown at $SRC_SHA (ssc-tools emit-rust)."
  echo "#![allow(warnings, clippy::all)]"
  cat "$LIB"
} > "$LIB.tmp" && mv "$LIB.tmp" "$LIB"

echo "regen-uniml-md: verifying cargo build -p uniml-md"
( cd "$ROOT" && cargo build -p uniml-md --quiet ) || {
  echo "regen-uniml-md: FAILED — the regenerated crate does not build; NOT leaving a broken tree unflagged" >&2
  exit 1
}
echo "regen-uniml-md: OK. git status of the crate:"
git -C "$ROOT" status --porcelain "$CRATE" | sed 's/^/  /' || true
