// GENERATED by scripts/regen-uniml-md.sh — do not edit.
// Source: scalascript uniml core+markup+markdown+rust at 726d07176111d1744d5b6fb9e31380a02fad5b2c (ssc-tools emit-rust).
#![allow(warnings, clippy::all)]
//! Crate library root.  Emitted by RustGen; do not edit by hand.

pub mod runtime;
pub mod value;
pub mod generated;
