// GENERATED by scripts/regen-uniml-md.sh — do not edit.
// Source: scalascript uniml core+markup+markdown+rust at 9f2b37e79e883fe33c267d70e3f5f9336f8853f7 (ssc-tools emit-rust).
#![allow(warnings, clippy::all)]
//! Crate library root.  Emitted by RustGen; do not edit by hand.

pub mod runtime;
pub mod value;
pub mod generated;
