// GENERATED by scripts/regen-uniml-md.sh — do not edit.
// Source: scalascript uniml core+markup+markdown+rust at d8003ab1052519eb77f9ace07b6d95ae1dc56f05 (ssc-tools emit-rust).
#![allow(warnings, clippy::all)]
//! Crate library root.  Emitted by RustGen; do not edit by hand.

pub mod runtime;
pub mod value;
pub mod generated;
